name: borgatrust
description: A Flutter app to connect the diaspora with trusted service makers.

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.17 # For onboarding screens
  shared_preferences: ^2.5.3 # For local data storage
  flutter_animate: ^4.5.2 # For slick animations
  google_fonts: ^6.2.1 # For Poppins font
  flutter_launcher_icons: ^0.14.3 # For custom app icon
  cupertino_icons: ^1.0.8 # Default Flutter icons
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # For code linting

flutter:
  uses-material-design: true

  # Assets for Afrocentric images (e.g., Ankara patterns, logos)
  assets:
    - assets/images/
    # - assets/images/ankara.png # Placeholder for Afrocentric background

  # Fonts setup for Poppins
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/borgatrust_logo.png"
  adaptive_icon_background: "#FFFFFF" # For Android adaptive icons   hyh